export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('skill').del()

  await knex('skill').insert([
    {
      character_id: 1,
      athletics: 0,
      intimidation: 0,
      acrobatics: 9,
      stealth: 9,
      performance: 9,
      taming: 11,
      investigation: -3,
      knowledge: -3,
      medicine: -3,
      crafting: -3,
      perception: -2,
      wilderness: -3,
      insight: -3,
      rhetoric: -2,
    },
    {
      character_id: 2,
      athletics: 7,
      intimidation: 4,
      acrobatics: 5,
      stealth: 6,
      performance: -2,
      taming: -2,
      investigation: 8,
      knowledge: 8,
      medicine: 7,
      crafting: 7,
      perception: 8,
      wilderness: 7,
      insight: 7,
      rhetoric: 8,
    },
    {
      character_id: 3,
      athletics: 7,
      intimidation: 10,
      acrobatics: 7,
      stealth: 7,
      performance: 0,
      taming: 0,
      investigation: 2,
      knowledge: 0,
      medicine: 0,
      crafting: 0,
      perception: 0,
      wilderness: 0,
      insight: 0,
      rhetoric: 0,
    },
    {
      character_id: 4,
      athletics: 2,
      intimidation: 2,
      acrobatics: 0,
      stealth: 1,
      performance: 17,
      taming: 18,
      investigation: 1,
      knowledge: 1,
      medicine: 3,
      crafting: 0,
      perception: 0,
      wilderness: 0,
      insight: 0,
      rhetoric: 1,
    },
  ])
}
